### ISSUE TITLE
Substitute cost

### ISSUE THREAD

**Issue by xuannt88** [laurikari/tre#115]
Hello,
Can you tell me how to calculate substitute cost. Is there any dictionary to replace characters ?

Thanks

**Comment by dag-erling** [comment]
The default substitution cost is 1, but you can set it [in the regular expression itself](https://laurikari.net/tre/documentation/regex-syntax/#approx-settings) and pass different defaults to [the matching function](https://laurikari.net/tre/documentation/regaexec/). The code for approximate matching is [here](https://github.com/laurikari/tre/blob/master/lib/tre-match-approx.c) and you can see the default parameters [here](https://github.com/laurikari/tre/blob/master/lib/regexec.c#L372-L384).
