### ISSUE TITLE
Position of insert/delete/subsitution character in matched result

### ISSUE THREAD

**Issue by xuannt88** [laurikari/tre#116]
Hello,
After get matching result, can we know which position in text is inserted/deleted or substitution.
Thanks,

**Comment by trushworth** [comment]
Hi,

 >Hello,
 >After get matching result, can we know which position in text is 
 >inserted/deleted or substitution.
 > Thanks,

This would be pretty complicated.

There can be different matching positions for subexpressions (which is 
why pmatch is an array), and there could be multiple different 
insert/delete/substituion locations for each subexpression match 
position.  The existing API would have to be extended, either to have 
some way to iterate over the locations or to have an array of some sort 
in the regmatch_t structure.  There would also probably need to be 
definitions for what type of insert/delete/substituion happened at each 
position, and maybe further detail such as what needed to be inserted or 
deleted or substituted.

So, not with the existing API.

**Comment by dag-erling** [comment]
Based on this and your previous question, it sounds like you're trying to do something like a sequence alignment. You may want to look into the [Needleman-Wunsch algorithm](https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm), it's quite easy to implement and can easily be modified to report substitution sites.
