### ISSUE TITLE
Question about approximate matching

### ISSUE THREAD

**Issue by georgekola** [laurikari/tre#2]
I am trying to do just approximate matching of a small string in a given larger string and return if there is a match based on the specified maximum error/cost. 

I found tre-agrep and the code I wrote based on the docs works fine.  Thanks for making this open-source library.

I do not need any regular expression support  -- I want to know if there is a way to optimize the call to int tre_regncomp(regex_t *preg, const char *regex, size_t len, int cflags) ? I would like to do it for two reasons 1. Performance (the code is on the critical path ) 2. I take arbitrary input and do matching and I am not escaping the search string  (Escaping would further slow things down and I do not know how to correctly do it).   Some pointers to which functions I should call/modify to accomplish what I want would be greatly appreciated.

Thanks,
George

**Comment by dag-erling** [comment]
Use the `REG_LITERAL` flag to avoid having to escape your search string. Performance will not be an issue.
