### ISSUE TITLE
./configure expects a ChangeLog

### ISSUE THREAD

**Issue by aberezin** [laurikari/tre#27]
Seems like ChangeLog was renamed to ChangeLog.old and that commit expected darcs to create a new ChangeLog file. But the darcs dependency was then removed. So I had to 
    cp ChangeLog.old ChangeLog 
to get ./configure to work

**Comment by dag-erling** [comment]
The configure script does not require the ChangeLog to exist, unless you ran `automake` manually without the `--foreign` option instead of running `./utils/autogen.sh` as documented.
