### ISSUE TITLE
Odd character problem with tre-agrep

### ISSUE THREAD

**Issue by nilsola** [laurikari/tre#28]
When agrep’ing a file with some odd characters on one
line the search seems to stop at that line and nothing
is found therafter.

Furhter info:
export LC_ALL=en_US.UTF-8
  <the trouble described below>
export LC_ALL=en_US.ISO8859-1
  <work as expected!>
unset LC_ALL
  <work as expected!>

so it seems to be a problem related to utf-8

I have reduced this to a testfile that I paste here in b64, 
it is only 4 lines:
eW91dHViZSBuaWxzb2xhYXhlbAp2aW1lbyBuaWxzb2xhQGFiYy5zZSAKbz8/4oCZcmVpbGx5
IGhlbUBuaWxzb2xhLnNlIApkYXRvcm1hZ2F6aW4gZG16bGFicyBtZWRpYXNob3cgbmlsc29s
YQo=

The simple testcase is simply like this:
  $ /usr/bin/grep datormagazin /tmp/test
  datormagazin dmzlabs mediashow nilsola
  $ echo $?
  0
  $ /usr/local/bin/agrep datormagazin /tmp/test
  $ echo $?
  1

Further details:
I have tested this on both openbsd 5.5 and 5.6 (when
installed with pkg_add) and on gentoo (added as a
package dev-libs/tre)
OpenBSD Version tre-0.8.0p0
gentoo version tre-0.8.0

Further tests 
match on two lines before works as expected:
  $ /usr/bin/grep nilsolaa /tmp/test
  youtube nilsolaaxel
  $ /usr/local/bin/agrep nilsolaa /tmp/test
  youtube nilsolaaxel

match on line before, strange behaviour:
  $ /usr/bin/grep vimeo /tmp/test
  vimeo nilsola@abc.se
  $ /usr/local/bin/agrep vimeo /tmp/test
  vimeo nilsola@abc.se 
  o���reilly hem@nilsola.se 
  datormagazin dmzlabs mediashow nilsola
  s%
  $ echo $?
  0

**Comment by dag-erling** [comment]
Appears to work as expected in the current version.
