### ISSUE TITLE
Logical AND instead of bitwise AND, tre-match-backtrack.c line 603

### ISSUE THREAD

**Issue by slaurel** [laurikari/tre#29]
lib/tre-match-backtrack.c

Line 603 reads:
if (stack->item.state->assertions && ASSERT_BACKREF)

It should use the bitwise operator &, as used elsewhere on line 415:
if (trans_i->state && trans_i->assertions & ASSERT_BACKREF)

**Comment by dag-erling** [comment]
This was fixed in fba4b22ac0c2.
