### ISSUE TITLE
possibly undefined macro

### ISSUE THREAD

**Issue by isomorphisms** [laurikari/tre#33]
```
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:8: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:14: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:40: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:516: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:517: error: possibly undefined macro: AC_LIBTOOL_TAGS
configure.ac:518: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:519: error: possibly undefined macro: AM_DISABLE_STATIC
configure.ac:520: error: possibly undefined macro: AC_PROG_LIBTOOL
```

When I went looking for the `Autoconf` documentation, I found...

http://lists.gnu.org/archive/html/autoconf/2010-01/msg00050.html

> That generally means that the package had an overquoted macro in its
> configure.ac.  You may be better off reporting this to the acl folks, to
> see if it is a bug in their files.
> 
> Meanwhile, here's the documentation of m4_pattern_allow [1].  However,
> adding m4_pattern_allow([AC_CONFIG_MACRO]) to configure.ac is probably not
> the right thing to do; but without seeing the context that caused the
> warning, I'm not sure what the best fix is.
> 
> [1] http://www.gnu.org/software/autoconf/manual/autoconf.html#Forbidden-Patterns

**Comment by dag-erling** [comment]
Unable to reproduce, probably caused by not running `./utils/autogen.sh` as documented.
