### ISSUE TITLE
File libtre.a generated?

### ISSUE THREAD

**Issue by jaime11** [laurikari/tre#60]
Hello,

Forgive me in advance if this is not libtre related, I am trying to install a program which is requiring the library libtre.a
I followed the manual to install libtre:
# Install libtre library
mkdir /data/mbp15ja/libtre
cd /data/mbp15ja/libtre
wget https://github.com/laurikari/tre/archive/master.zip
unzip master.zip
cd tre-master/
./utils/autogen.sh
mkdir /data/mbp15ja/tre-0.8.0
./configure --prefix /data/mbp15ja/tre-0.8.0
make
make install

Although the file lib/libtre.la seems to be created, the file lib/libtre.a doesn't exist. 
Is it possible that this file was created in earlier versions but not in this one? Is it a particular file created by other packages such as libtre-devel?

Thanks in advance!

**Comment by gdavidbutler** [comment]
Add --enable-static to ./configure (it isn't enabled by default).
