### ISSUE TITLE
Add option for '$' to zero match before MS Window's default line ending (CR LF = \r\n)

### ISSUE THREAD

**Issue by RaiKoHoff** [laurikari/tre#63]
In case of option REG_NEWLINE:
"... The match-end-of-line operator $ matches the empty string immediately before a newline ('\n') as well as the empty string at the end of the string (but see the REG_NOTEOL regexec() flag). ..."

Default line ending chars on MS Window systems are both: CR LF (`\r\n`).
So it would be fine, to have an option (REG_WIN_NEWLINE) so that the match-end-of-line operator $ matches the empty string immediately before the window's newline (CR LF ; `\r\n`)
In this case, the dot (`.`) should neither match `\r` nor `\n`.

Maybe also an option for systems, where the line-end char is CR (`\r`) only ?

**Comment by dag-erling** [comment]
The C line ending is `\n`. On systems that use different conventions, the C library will convert between C line endings and OS line endings when reading from or writing to files opened in text mode.
