### ISSUE TITLE
configure.ac:516: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.

### ISSUE THREAD

**Issue by akbar20gh** [laurikari/tre#66]
Hi dears
when I want to install and run `sudo ./utils/autogen.sh`
it's Erorr
`Replacing @TRE_VERSION@ by 0.8.0 to python/setup.py
Replacing @TRE_VERSION_1@ by 0 to python/setup.py
Replacing @TRE_VERSION_2@ by 8 to python/setup.py
Replacing @TRE_VERSION_3@ by 0 to python/setup.py
Replacing @TRE_VERSION@ by 0.8.0 to win32/tre-config.h
Replacing @TRE_VERSION_1@ by 0 to win32/tre-config.h
Replacing @TRE_VERSION_2@ by 8 to win32/tre-config.h
Replacing @TRE_VERSION_3@ by 0 to win32/tre-config.h
configure.ac:516: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:516: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:516: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
`
what's wrong?
how can fix it?

**Comment by forskning** [comment]
I have gettext-0.19.8.1.

Try running 'grep -r MKDIR /usr/share/aclocal'.

If that returns output for intl.m4 and po.m4 with AC_PROG_MKDIR_P then I wouldn't worry about it.

https://nurmi-labs.blogspot.com/2019/05/tre.html

**Comment by dag-erling** [comment]
This warning originates from Gettext and is harmless.
