### ISSUE TITLE
Certificate expired on https://laurikari.net

### ISSUE THREAD

**Issue by DmitryFromDubna** [laurikari/tre#82]
Hello! Could you please renew the certificate on https://laurikari.net/tre/ ? It has expired a couple weeks ago:

Your connection is not private
Attackers might be trying to steal your information from laurikari.net (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

Thank you!
Dmitry

**Comment by DmitryFromDubna** [comment]
Certificate has been renewed, closing the issue.

**Comment by DmitryFromDubna** [comment]
Hello; the certificate has expired again, so I can't open https://laurikari.net/tre in a browser. Specifically, https://laurikari.net/tre/documentation/regex-syntax/ is what I need to use. Is it possible to put that page into the GutHub repo, so it stays available? Thank you!

**Comment by ryandesign** [comment]
The certificate is currently valid again.
