### ISSUE TITLE
Create tags and releases

### ISSUE THREAD

**Issue by ryandesign** [laurikari/tre#86]
0.8.0 was released in 2009 but there are no [tags](https://github.com/laurikari/tre/tags) or [releases](https://github.com/laurikari/tre/releases) for that or any preceding version in this repository. Please create them and attach the original distfiles to the releases. Preserving history is important.

**Comment by dag-erling** [comment]
I've retroactively created a tag for v0.8.0. Note that it predates the switch from darcs to git.
