### ISSUE TITLE
Build failure on Adélie Linux

### ISSUE THREAD

**Issue by Elizafox** [laurikari/tre#89]
Hello,

TRE fails to build on Adélie Linux with `gettext-tiny`: https://github.com/sabotage-linux/gettext-tiny/issues/61

The fix is pretty simple: replace `AC_CONFIG_AUX_DIR(utils)` with `AC_CONFIG_AUX_DIR([utils])` in `configure.ac`. If you want, I will file a pull request, but it's a trivial fix, so I don't know if it's worth it.

**Comment by trushworth** [comment]
Hi,

I'll have a look at this as soon as I can get my testing environment
back up.  With any luck that will be by 2023/06/16 late in the day.

No need for a PR, as you say it's a trivial fix.  Thanks!

On Wed, Jun 14, 2023 at 10:56:49PM -0700, Elizabeth Myers wrote:
> Hello,
> 
> TRE fails to build on Adélie Linux with `gettext-tiny`: https://github.com/sabotage-linux/gettext-tiny/issues/61
> 
> The fix is pretty simple: replace `AC_CONFIG_AUX_DIR(utils)` with `AC_CONFIG_AUX_DIR([utils])` in `configure.ac`. If you want, I will file a pull request, but it's a trivial fix, so I don't know if it's worth it.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/laurikari/tre/issues/89
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

Cheers,
--
Tom Rushworth

**Comment by trushworth** [comment]
I've made the suggested change to configure.ac, and everything builds and tests OK on both Linux (Mint) and FreeBSD, so I've committed and pushed the change and will close this issue.  Thank you for the fix!
